### PR TITLE
Secure storage

### PR DESCRIPTION
**Pull request by lextiz**
@florianlenz Do not merge please. The code is ready for initial code review, but lacks tests, documentation and comments.

 - Secure storage implementation (https://github.com/Bit-Nation/BITNATION-Panthalassa-TS/issues/3)
   - For NodeJS platform
   - For react-native platform (not tested at all, needs integration with react-native)
 - Jest framework for tests
 - Tests for secure storage
 - VScode run configuration for debugging jest tests

Notes:
 - Browsers can be easily supported as well: https://github.com/bealearts/secure-storage-js
 - While using react-native is justified for integration with mobile platforms (OS-specific password prompts, bio-metric authentication), support of multiple platforms has a negative impact on the security of the whole solution. We can discuss it in person.

### CODE REVIEW

**Comment by florianlenz** [comment]
Hi,

thank you for the time you put into this. It look's great so far. When i run "npm run build" i am getting a few error's regarding type mismatching. Can you verify that on your working copy?

**Comment by lextiz** [comment]
Verified, it is ok, I will handle it at last.

**Comment by lextiz** [comment]
There still will be one transpilation error until https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20157 is merged.

**Comment by lextiz** [comment]
@florianlenz Looks good to me, IMO it can be merged.

**Comment by florianlenz** [comment]
Hi,
yes, travis CI is already on my todo list. I will wait with this merge till your fix for the "copyFileSync" method is merged. Can you please update the project dependencies when they merged it? 

Thank you very much

**Comment by florianlenz** [comment]
@lextiz 
Can you please change the copyFileSync function to something that can be used with node 6.11.3 (the copyFileSync function is included in node 8.5.0)? I am sorry that i forgot to mention the node js version. I pinned it now in the package.json. Also i updated the develop branch, it describe's how to use the docker setup (which use node 6.11.3).

**Comment by lextiz** [comment]
@florianlenz Cool. I will not have access to computer for next 2 weeks, so in case you want to finish the PR you are welcome, otherwise I will finish it after I come back from vacation. There is still a little chance I can jump to DevCon, so hopefully see you there.

**Comment by florianlenz** [comment]
@lextiz thx for your contribution. I dropped you a message on slack regarding the devcon. I would be happy to see you there :)

**Pull request merged**
